language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm install
- npm run build
true:
  branch: master
deploy:
  provider: heroku
  app: tahaappname
  api_key:
    secure: HatvugYT5dHHQNwDtg59qi0vvb0h76msuoH23f4Y0ejMvqt+mz0dTgZdMtxjTkd6GQF5UKd1375NcRWHASfJzzhCsMkZKZ58YzjT/bi7Q5nllwnZbi/I7bgOKGLLVdyBlhdbXCmPzajoA6ANv0Jzf3M1M+GmRYrHcNVIKTQ/op7Dc0THgjbaMAy8caiITg7tyxMVWjotDUa+4RvVxrvjW2f7SoLVCFVbq08ySLwBNuvA7o3ZvKZjBvJQg5UkO1D2kNG5A0+g2Vo0fM4h3Wthrs909Vb7ntpq6bWPloD35C8BlY/LHR7QdRgH/A2olEXdzlVmGjGzqe+LDCvydtxLQl/AHFOS+IlXvIcmRHCEkbkEHtkk544oCrjAz66HqGvm1OaMQ+h3Psqzsrd6iKfCDw5B7zivRKNSgKh+WMNpJk1pkP58OswPkFMg9WDKZEU1k4On2W3uZqCnQWDTxrCSbKeo+dl4GLtqQUoBeuMup1c9qY0eRnY+5ahz5BwIfOBE3Tq2KPIEZEgaMI3uckNiyU2SXyrPFTXWNVCGGxqRJXS9J+cs7hmWN2WM1Au4mHBbxW6HW41qZ28VESSArN18MHEtjFi47a3uwnUpjgiN9M95o881aJP6ESXVVm0Xo5xIFQJqU7bGmFna6EIaLC/2Rd/oZGSCVsqOL/0F0BdZARw=
