language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm install
- npm run build
- npm run deploy
true:
  branch: master
deploy:
  provider: heroku
  app: tahaappname
  api_key:
    secure: a1VeynWFTSmxtj+pgHuYjfCfvV5CBeg8QDSEUvbSDsUsVH/qr7KkqrBPbisXt6F/xJ44e3fjr/p/bsUWyZr+2ZjnWWhXsGHsOgY4KdyW+UI6vfmYff5SUgvYG4z0yvw+hfx0ul4bliKBOdCS/yL4O6+8tNX6Qb//QpjZn5j49VEsKJVpHLeE32V9X2myeQjuuSqTTwRy84x7o3uC5OZTSkJGgFqJryvLGFCuO7Xrev5ZUPRLAHfkGd8ooD3NT5FkUbO7lBr6Tlgb83eURbqtl4Yv+buRY8YIKkk0XdlM3vRZooKJeO9GiGGBr06QiSerQtvIkos7smpnjD8vIJFERiJnG4UUbCujFrYBA/kPltYrUegizioCVqQro9SemIw7Xi/jkXH1LEaBnxnxWlfQhAAXERQTBSXWvUGCOs3zmU//T2EjjPjkAEAAXelwC+sTbkmD6EFSg6LMyuMUFpFGf3lmQZ1gOQ4iGwO7Wd2td6RFNQMvlsVXUvAFf9Z7f2WV5Ql5FiLv29F0sRT/SUkoUYFKLehV60/1Trq1MuaSlEmlF83A11q/hkJTui1wK9SCnlnv6ZKJmGXtkQzL7PpA9HKrFU1+vS3zm2g4PIx3aTA/cSGnscNSbcCYvuk+mqUlaRc935AWjYwwGE4M1VO55voga7H5C+pJK0mhHkpRhu0=
